apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/ootb: 'true'
  annotations:
    description: vLLM is a high-throughput and memory-efficient inference and serving engine for LLMs 
    openshift.io/display-name: vLLM ServingRuntime for KServe
    openshift.io/provider-display-name: Red Hat, Inc.
    tags: rhods,rhoai,kserve,servingruntime
    template.openshift.io/documentation-url: https://github.com/opendatahub-io/vllm
    template.openshift.io/long-description: This template defines resources needed to deploy vLLM ServingRuntime with KServe in Red Hat OpenShift AI
    opendatahub.io/modelServingSupport: '["single"]'
    opendatahub.io/apiProtocol: 'REST'
  name: vllm-runtime-template
objects:
  - apiVersion: serving.kserve.io/v1alpha1
    kind: ServingRuntime
    metadata:
      name: vllm-runtime
      annotations:
        openshift.io/display-name: vLLM ServingRuntime for KServe
        opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
      labels:
        opendatahub.io/dashboard: 'true'
    spec:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
      multiModel: false
      supportedModelFormats:
        - autoSelect: true
          name: vLLM
      containers:
        - name: kserve-container
          image: $(vllm-image)
          args:
            - '--port=8080'
            - '--model=/mnt/models'
            - '--served-model-name={{.Name}}'
          env:
            - name: HF_HUB_CACHE
              value: /tmp
          readinessProbe:
            httpGet: 
              port: 8080
              path: /health
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet: 
              port: 8080
              path: /health
            periodSeconds: 100
            timeoutSeconds: 8
          startupProbe:
            httpGet:
              port: 8080
              path: /health
            # Allow 12 mins to start
            failureThreshold: 24
            periodSeconds: 30
          ports:
            - containerPort: 8080
              protocol: TCP
